### ISSUE TITLE
Custom states don't seem to render

### ISSUE THREAD

**Issue by j8ter** [OkamiWong/obsidian-custom-state-for-task-list#7]
Thanks for this great plugin! I seem to have an issue with the emoji not rendering and the task not recognized by Dataview.

I'm on Obsidian 1.6.7, I have your plugin installed and enabled, I have the default custom states and have the Tasks plugin installed and enabled as well.

Screenshot for reference:

![image](https://github.com/user-attachments/assets/84966000-efde-420a-ad00-ab3a686c648a)

**Comment by Mcreepers** [comment]
I'm using obsidian v1.7.4,this plugin still don't work

**Comment by OkamiWong** [comment]
Sorry for the late response.

I verified that by updating the plugin to 1.0.3, this issue is fixed in Obsidian v1.7.7.

**Comment by joost8** [comment]
Thanks, here I have Obsidian v1.6.7 and the plugin version is v1.0.3. So maybe I have to wait?

**Comment by OkamiWong** [comment]
Hi @joost8 . Theoretically v1.0.3 should also work on Obsidian v1.6.7. Are the custom states still not rendered on your side?

**Comment by joost8** [comment]
Unfortunately not, I still get these results. I reinstalled the plugin and have it set to only the defaults.

![image](https://github.com/user-attachments/assets/4fe71325-babe-4332-b5b6-2cb615d3a87a)

**Comment by OkamiWong** [comment]
Noted. Let me check.

**Comment by OkamiWong** [comment]
Hi @joost8 . I couldn't reproduce the rendering bug with Obsidian v1.6.7 and v1.0.3 of this plugin.

Could you show me the list of all plugins installed? I am guessing maybe there is a conflict with other plugins.

**Comment by joost8** [comment]
Of course, this is what I have installed:

Core plugins:
![image](https://github.com/user-attachments/assets/db416941-40bd-4363-b960-976cca55fd49)

Community plugins:
![image](https://github.com/user-attachments/assets/0cb34479-0e22-43e8-bb06-d75671a6a9d4)
